name: Python CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run data script on sample
        run: |
          python src/load_meteorites.py --input data/meteorites_sample.csv
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs-and-images
          path: |
            outputs/**
            images/**
