name: Python CI

on:
  push:
    branches:
      - '**'   # run on pushes to any branch
  pull_request:
    branches:
      - '**'   # run on PRs to any branch
  workflow_dispatch:   # allow manual trigger from Actions tab


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        python main.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: outputs
        path: |
          outputs/
          images/
